#workflow configuration test
name: Hello World


#Events
on:
    push:
     branches:
      - main
      

jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
          -  name: checkout files 
             run: pwd && ls -al
          - uses: actions/checkout@v4.2.2
          - run: pwd && ls -al
          - run: node index.js
          
   
